Prevent clobbering worktree files when running on the committed

diff --git a/beautify b/beautify
--- a/beautify
+++ b/beautify
@@ -47,6 +47,12 @@ do
     (--on-committed)
         against=HEAD^1
         do_commit=true
+        # Ensure that worktree and staging area is clean to prevent file clobbering
+        if ! eval git diff-files --quiet --ignore-submodules --diff-filter=$filter               -- $extension ||
+           ! eval git diff-index --quiet --ignore-submodules --diff-filter=$filter --cached HEAD -- $extension
+        then
+            die "error: Worktree or staging area not clean. Preventing clobbering of files."
+        fi
         shift
         ;;
     (--no-commit)
