Support Clang & (experimental) macOS in Score-P
* Make Fortran compilers optional
* Make compiler instrumentation optional (was only partially disabled before)
* Make OpenMP fully optional again
* Allow to disable Online Access at configure time
* Make all file names case-insensitive
* Add a 'Link mode: static=$enable_static, shared=$enabled_shared' config summary line

Submitts review:277, see review:276.


Subversion: revision:14549

diff --git a/test/constructor_checks/run_constructor_checks.sh.in b/test/constructor_checks/run_constructor_checks.sh.in
--- a/test/constructor_checks/run_constructor_checks.sh.in
+++ b/test/constructor_checks/run_constructor_checks.sh.in
@@ -45,38 +45,32 @@ cleanup()
 }
 trap cleanup EXIT
 
+languages="c cxx"
+@SCOREP_HAVE_FC_TRUE@languages="$languages f"
+
 paradigm_threads="none"
 @HAVE_OPENMP_SUPPORT_TRUE@paradigm_threads="$paradigm_threads omp"
 
 for thread in $paradigm_threads
 do
-    cleanup
-    printf "Running Score-P constructor check for C ($thread) "
-    $dir/test_constructor_check_${thread}_c$EXEEXT 2>&1 >/dev/null |
-        $GREP -q 'initialized via constructor' &&
-        echo " ok" ||
-        {
-            echo " FAILED"
-            exit 1
-        }
 
-    cleanup
-    printf "Running Score-P constructor check for C++ ($thread) "
-    $dir/test_constructor_check_${thread}_cxx$EXEEXT 2>&1 >/dev/null |
-        $GREP -q 'initialized via constructor' &&
-        echo " ok" ||
-        {
-            echo " FAILED"
-            exit 1
-        }
+    for l in $languages
+    do
+        case $l in
+        (c)   L=C       ;;
+        (cxx) L=C++     ;;
+        (f)   L=Fortran ;;
+        esac
 
-    cleanup
-    printf "Running Score-P constructor check for Fortran ($thread) "
-    $dir/test_constructor_check_${thread}_f$EXEEXT 2>&1 >/dev/null |
-        $GREP -q 'initialized via constructor' &&
-        echo " ok" ||
-        {
-            echo " FAILED"
-            exit 1
-        }
+        cleanup
+        printf "Running Score-P constructor check for $L ($thread) "
+        $dir/test_constructor_check_${thread}_$l$EXEEXT 2>&1 >/dev/null |
+            $GREP -q 'initialized via constructor' &&
+            echo " ok" ||
+            {
+                echo " FAILED"
+                exit 1
+            }
+    done #languages
+
 done #thread
