Improve silent rules and adopt colors

diff --git a/doc/Makefile.inc.am b/doc/Makefile.inc.am
--- a/doc/Makefile.inc.am
+++ b/doc/Makefile.inc.am
@@ -9,7 +9,7 @@
 ## Copyright (c) 2009-2011,
 ## Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 ##
-## Copyright (c) 2009-2011, 2019,
+## Copyright (c) 2009-2011, 2019-2020,
 ## Technische Universitaet Dresden, Germany
 ##
 ## Copyright (c) 2009-2011,
@@ -67,22 +67,25 @@ doxygen-user-install:
 doxygen-user-generate: doxygen-user-pdf doxygen-user-html-compress copy-revision-file-to-dist
 
 update-revision:
-	cd $(srcdir) && git describe --always --dirty > "build-config/REVISION"
+	@$(am__tty_colors); \
+        if $(AM_V_P); then echo "cd $(srcdir) && git describe --always --dirty > 'build-config/REVISION'"; \
+        else               echo "  GEN      $${mgn}$(srcdir)/build-config/REVISION$$std"; fi; \
+        cd $(srcdir) && git describe --always --dirty > "build-config/REVISION"
 
 copy-revision-file-to-dist:
-	@$(MKDIR_P) "$(distdir)/build-config/"
-	@cp -p "$(srcdir)/build-config/REVISION" "$(distdir)/build-config/"
-	@case `cat "$(distdir)/build-config/REVISION"` in *-dirty)                           \
+	$(AM_V_at)$(MKDIR_P) "$(distdir)/build-config/" || exit 1;                           \
+        cp -p "$(srcdir)/build-config/REVISION" "$(distdir)/build-config/" || exit $$?;      \
+        case `cat "$(distdir)/build-config/REVISION"` in *-dirty)                            \
             echo >&2 "WARNING: distribution does not match a single, unmodified revision.";; \
         esac
 
 doxygen-user-html-compress:
-	if test -d "$(USER_DOC_DIR)/html"; then                               \
-	    cd "$(USER_DOC_DIR)"; tar czvf html.tar.gz html; rm -rf html/;    \
-	fi
+	$(AM_V_at)if test -d "$(USER_DOC_DIR)/html"; then                     \
+            cd "$(USER_DOC_DIR)"; tar czf html.tar.gz html; rm -rf html/;     \
+        fi
 
 doxygen-project-number: update-revision
-	echo "PROJECT_NUMBER = \"@PACKAGE_VERSION@ (revision `cat $(srcdir)/build-config/REVISION`)\"" > doc/doxygen-project-number.cfg
+	$(AM_V_at)echo "PROJECT_NUMBER = \"@PACKAGE_VERSION@ (revision `cat $(srcdir)/build-config/REVISION`)\"" > doc/doxygen-project-number.cfg
 
 CLEANFILES += doc/doxygen-project-number.cfg
 
@@ -92,14 +95,26 @@ doxygen-user-clean:
 
 if HAVE_DOXYGEN
 
+SCOREP_V_DOXYGEN = $(scorep__v_DOXYGEN_@AM_V@)
+scorep__v_DOXYGEN_ = $(scorep__v_DOXYGEN_@AM_DEFAULT_V@)
+scorep__v_DOXYGEN_0 = @$(am__tty_colors); echo "  DOXYGEN  $${blu}$@$$std";
+scorep__v_DOXYGEN_1 = 
+
+SCOREP_V_DEVNULL = $(scorep__v_DEVNULL_@AM_V@)
+scorep__v_DEVNULL_ = $(scorep__v_DEVNULL_@AM_DEFAULT_V@)
+scorep__v_DEVNULL_0 = >/dev/null
+scorep__v_DEVNULL_1 = 
+
 doxygen-user: doxygen-project-number doc/doxygen-user/main.dox doc/doxygen-user.cfg
-	$(MKDIR_P) "$(USER_DOC_DIR)/tags"
-	echo "OUTPUT_DIRECTORY = $(USER_DOC_DIR)" > doc/doxygen-user-at-make-time.cfg
-	echo "GENERATE_TAGFILE = $(USER_DOC_DIR)/tags/@PACKAGE@.tag" >> doc/doxygen-user-at-make-time.cfg
-	cat doc/doxygen-project-number.cfg doc/doxygen-user-at-make-time.cfg doc/doxygen-user.cfg > doc/doxygen-user-html.cfg
-	$(MKDIR_P) "$(USER_DOC_DIR)/html"
-	cp $(abs_srcdir)/doc/images/* $(USER_DOC_DIR)/html
-	$(DOXYGEN) doc/doxygen-user-html.cfg
+	$(AM_V_at)$(MKDIR_P) "$(USER_DOC_DIR)/tags"
+	$(AM_V_at)echo "OUTPUT_DIRECTORY = $(USER_DOC_DIR)" > doc/doxygen-user-at-make-time.cfg
+	$(AM_V_at)echo "GENERATE_TAGFILE = $(USER_DOC_DIR)/tags/@PACKAGE@.tag" >> doc/doxygen-user-at-make-time.cfg
+	$(AM_V_at)cat doc/doxygen-project-number.cfg doc/doxygen-user-at-make-time.cfg doc/doxygen-user.cfg > doc/doxygen-user-html.cfg
+	$(AM_V_at)$(MKDIR_P) "$(USER_DOC_DIR)/html"
+	$(AM_V_at)cp $(abs_srcdir)/doc/images/* $(USER_DOC_DIR)/html
+	$(AM_V_at)if $(AM_V_P); then echo "QUIET = NO"; \
+				else echo "QUIET = YES"; fi >>doc/doxygen-user-html.cfg
+	$(SCOREP_V_DOXYGEN)$(DOXYGEN) doc/doxygen-user-html.cfg
 
 CLEANFILES += doc/doxygen-user-html.cfg doc/doxygen-user-at-make-time.cfg doxygen.err
 
@@ -112,17 +127,27 @@ endif !HAVE_DOXYGEN
 
 if HAVE_DOXYGEN_LATEX
 
+SCOREP_V_pdflatex    = $(scorep__v_pdflatex_@AM_V@)
+scorep__v_pdflatex_  = $(scorep__v_pdflatex_@AM_DEFAULT_V@)
+scorep__v_pdflatex_0 = -interaction batchmode
+scorep__v_pdflatex_1 = -interaction nonstopmode
+
 doxygen-user-pdf: doxygen-user
-	cat doc/doxygen-user-html.cfg > doc/doxygen-user-pdf.cfg
-	echo "ENABLED_SECTIONS = LATEX" >> doc/doxygen-user-pdf.cfg
-	echo "GENERATE_HTML    = NO"    >> doc/doxygen-user-pdf.cfg
-	cp $(DOC_SRC_DIR)/license.tex $(USER_DOC_DIR)/pdf/
-	-cp $(DOC_SRC_DIR)/images/project_logo.pdf $(USER_DOC_DIR)/pdf/
-	$(DOXYGEN) doc/doxygen-user-pdf.cfg
-	cd "$(USER_DOC_DIR)/pdf" && \
-	make &&                     \
-	mv refman.pdf ../ &&        \
-	rm -f * &&                  \
+	$(AM_V_at)cat doc/doxygen-user-html.cfg > doc/doxygen-user-pdf.cfg
+	$(AM_V_at)echo "ENABLED_SECTIONS = LATEX" >> doc/doxygen-user-pdf.cfg
+	$(AM_V_at)echo "GENERATE_HTML    = NO"    >> doc/doxygen-user-pdf.cfg
+	$(AM_V_at)cp $(DOC_SRC_DIR)/license.tex $(USER_DOC_DIR)/pdf/
+	-$(AM_V_at)cp $(DOC_SRC_DIR)/images/project_logo.pdf $(USER_DOC_DIR)/pdf/
+	$(AM_V_at)echo "LATEX_CMD_NAME = \"pdflatex -file-line-error $(SCOREP_V_pdflatex)\"" >>doc/doxygen-user-pdf.cfg
+	$(AM_V_at)if $(AM_V_P); then echo "QUIET = NO"; \
+	          else               echo "QUIET = YES"; \
+	                             echo "MAKEINDEX_CMD_NAME = \"makeindex -q\""; \
+	          fi >>doc/doxygen-user-pdf.cfg
+	$(SCOREP_V_DOXYGEN)$(DOXYGEN) doc/doxygen-user-pdf.cfg
+	$(AM_V_at)cd "$(USER_DOC_DIR)/pdf" && \
+	make $(SCOREP_V_DEVNULL) &&           \
+	mv refman.pdf ../ &&                  \
+	rm -f * &&                            \
 	mv ../refman.pdf @PACKAGE@.pdf
 
 else !HAVE_DOXYGEN_LATEX
@@ -142,14 +167,14 @@ doxygen-user-generate:
 doxygen-user-pdf:
 
 doxygen-user-install:
-	if test -f "$(DOC_SRC_DIR)/html.tar.gz"; then                                   \
+	$(AM_V_at)if test -f "$(DOC_SRC_DIR)/html.tar.gz"; then                         \
             $(MKDIR_P) $(DESTDIR)$(docdir);                                             \
             $(INSTALL_DATA) $(DOC_SRC_DIR)/html.tar.gz $(DESTDIR)$(docdir)/html.tar.gz; \
-	    cd $(DESTDIR)$(docdir);                                                     \
-            tar xzvf html.tar.gz;                                                       \
-	    rm -f html.tar.gz;                                                          \
-	fi
-	if test -d "$(DOC_SRC_DIR)"; then                                                   \
+            cd $(DESTDIR)$(docdir);                                                     \
+            tar xzf html.tar.gz;                                                        \
+            rm -f html.tar.gz;                                                          \
+        fi
+	$(AM_V_at)if test -d "$(DOC_SRC_DIR)"; then                                         \
             cd $(DOC_SRC_DIR);                                                              \
             dirs="pdf tags";                                                                \
             cd -;                                                                           \
diff --git a/test/instrumenter_checks/check-instrumentation.sh.in b/test/instrumenter_checks/check-instrumentation.sh.in
--- a/test/instrumenter_checks/check-instrumentation.sh.in
+++ b/test/instrumenter_checks/check-instrumentation.sh.in
@@ -262,11 +262,35 @@ fi
 
 
 # --- Control output ---
+color_enabled=no
+if [ "$AM_COLOR_TESTS" = no ]; then
+    color_enabled=no
+elif [ "$AM_COLOR_TESTS" = always ]; then
+    color_enabled=yes
+elif [ "$TERM" != dumb ] && [ -t 1 ]; then
+    color_enabled=yes
+fi
+
+if test $color_enabled = yes; then
+    # e for ascii escape sequence. Add some prefix to avoid name clashes when being sourced.
+    red='[0;31m'
+    grn='[0;32m'
+    blu='[1;34m'
+    mgn='[0;35m'
+    std='[0m'
+else
+    red=''
+    grn=''
+    blu=''
+    mgn=''
+    std=''
+fi
+
 if test -n "${VERBOSE}"; then
     echo "$CHECK"
     set -x
 else
-    echo "  CHECK   ${EXE}"
+    echo "  CHECK   ${grn}${EXE}${std}"
 fi
 
 
@@ -357,9 +381,9 @@ fi
 
 # --- Compare results ---
 if test "${INST_EXPECTED}" != "${INST_FOUND}"; then
-    echo "ERROR: Instrumentation differs from expected result!" >&2
-    echo "       Expected: ${INST_EXPECTED:-<none>}" >&2
-    echo "       Found   : ${INST_FOUND:-<none>}" >&2
+    echo "${red}ERROR: Instrumentation differs from expected result!${std}" >&2
+    echo "       Expected: ${blu}${INST_EXPECTED:-<none>}${std}" >&2
+    echo "       Found   : ${mag}${INST_FOUND:-<none>}${std}" >&2
     exit 1
 fi
 
