Removed the scorep-config-tool-local target. Tests sourceing the scorep_config.dat use variable substitution at configure time instead
Subversion: revision:3211

diff --git a/test/adapters/user/C++/run_user_cxx_test.sh.in b/test/adapters/user/C++/run_user_cxx_test.sh.in
--- a/test/adapters/user/C++/run_user_cxx_test.sh.in
+++ b/test/adapters/user/C++/run_user_cxx_test.sh.in
@@ -18,42 +18,45 @@
 ## file       run_filter_test.sh
 ## maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 
-# Get SRC_ROOT and OTF2_PRINT
-make clean-local-scorep-config-tool
-make scorep-config-tool-local
-. ./scorep_config.dat
+cleanup()
+{
+   rm -f config.h user_cxx_test 
+   rm -rf scorep-measurement-tmp
+}
+trap cleanup EXIT
+
+OTF2_PRINT=@OTF2_BINDIR@/otf2-print
+SRC_ROOT=@abs_top_srcdir@/..
+CXX=@CXX@
+OPENMP_CFLAGS=@OPENMP_CFLAGS@
 
 # Execute test without OpenMP and compiler instrumentation (only user)
 echo "/* Dummy */" > config.h
 ./scorep -v --build-check --user --nocompiler $CXX -I. -o user_cxx_test $SRC_ROOT/test/adapters/user/C++/user_test.cxx
 if [ ! -e user_cxx_test ]; then
-    rm -f config.h
+    echo "Failed to build user_cxx_test with user instrumention only"
     exit 1
 fi
 
 ./user_cxx_test
 if [ $? -ne 0 ]; then
-    rm -rf scorep-measurement-tmp config.h user_cxx_test
+    echo "Failed to run user_cxx_test with user instrumention only"
     exit 1
 fi
-rm -f config.h user_cxx_test
-
-exit 0
 
 # Execute test with OpenMP compiler and user instrumentation.
 echo "/* Dummy */" > config.h
 ./scorep -v --build-check --user --nocompiler $CXX $OPENMP_CFLAGS -I. -g -o user_cxx_test $SRC_ROOT/test/adapters/user/C++/user_test.cxx
 if [ ! -e user_cxx_test ]; then
-    rm -f config.h
+    echo "Failed to build user_cxx_test with user and compiler instrumentation"
     exit 1
 fi
 
 ./user_cxx_test
 if [ $? -ne 0 ]; then
-    rm -rf scorep-measurement-tmp config.h user_cxx_test
+    echo "Failed to run user_cxx_test with user and compiler instrumentation"
     exit 1
 fi
-rm -f config.h user_cxx_test
 
 exit 0
 
diff --git a/test/adapters/user/C/run_selective_test.sh.in b/test/adapters/user/C/run_selective_test.sh.in
--- a/test/adapters/user/C/run_selective_test.sh.in
+++ b/test/adapters/user/C/run_selective_test.sh.in
@@ -18,18 +18,23 @@
 ## file       run_selective_test.sh
 ## maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 
-# Get SRC_ROOT and OTF2_PRINT
-make clean-local-scorep-config-tool
-make scorep-config-tool-local
-. ./scorep_config.dat
 
+OTF2_PRINT=@OTF2_BINDIR@/otf2-print
+SRC_ROOT=@abs_top_srcdir@/..
 RESULT_DIR=scorep-selective-test-dir
-rm -rf $RESULT_DIR
+
+cleanup()
+{
+    rm -rf scorep-measurement-tmp
+    rm -rf $RESULT_DIR
+    rm -f trace.txt
+}
+trap cleanup EXIT
 
 # Execute selective test
 SCOREP_EXPERIMENT_DIRECTORY=$RESULT_DIR SCOREP_ENABLE_PROFILING=false SCOREP_ENABLE_TRACING=true SCOREP_SELECTIVE_CONFIG_FILE=$SRC_ROOT/test/adapters/user/C/selective.cfg ./selective_test
 if [ $? -ne 0 ]; then
-    rm -rf scorep-measurement-tmp start_ls.log
+    echo "selective_test exited with errors."
     exit 1
 fi
 
@@ -37,19 +42,16 @@ fi
 $OTF2_PRINT $RESULT_DIR/traces.otf2 | LC_ALL=C grep '^\(ENTER\|LEAVE\) ' > trace.txt
 if [ x`grep -c loop trace.txt` = x16 ]; then
   if [ x`grep -c foo trace.txt` = x16 ]; then
-    rm -rf trace.txt $RESULT_DIR
     exit 0;
   else
     echo "Uncorrect number of events for 'foo'."
     echo "16 expected but `grep -c loop trace.txt` occured"
-    rm trace.txt
     exit 1
   fi
 fi
 
 echo "Uncorrect number of events for 'foo'."
 echo "16 expected but `grep -c loop trace.txt` occured"
-rm trace.txt
 exit 1
 
 
diff --git a/test/adapters/user/Fortran/run_selective_test.sh.in b/test/adapters/user/Fortran/run_selective_test.sh.in
--- a/test/adapters/user/Fortran/run_selective_test.sh.in
+++ b/test/adapters/user/Fortran/run_selective_test.sh.in
@@ -18,18 +18,24 @@
 ## file       run_selective_test.sh
 ## maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 
-# Get SRC_ROOT and OTF2_PRINT
-make clean-local-scorep-config-tool
-make scorep-config-tool-local
-. ./scorep_config.dat
 
+OTF2_PRINT=@OTF2_BINDIR@/otf2-print
+SRC_ROOT=@abs_top_srcdir@/..
 RESULT_DIR=scorep-selective-f-test-dir
-rm -rf $RESULT_DIR
+
+cleanup()
+{
+    rm -rf scorep-measurement-tmp
+    rm -rf $RESULT_DIR
+    rm -f trace.txt
+}
+trap cleanup EXIT
+
 
 # Execute selective test
 SCOREP_EXPERIMENT_DIRECTORY=$RESULT_DIR SCOREP_ENABLE_PROFILING=false SCOREP_ENABLE_TRACING=true SCOREP_SELECTIVE_CONFIG_FILE=$SRC_ROOT/test/adapters/user/Fortran/selective.cfg ./user_f_test
 if [ $? -ne 0 ]; then
-    rm -rf scorep-measurement-tmp start_ls.log
+    echo "Runnning user_f_test with selective measurment failed"
     exit 1
 fi
 
@@ -37,19 +43,16 @@ fi
 $OTF2_PRINT $RESULT_DIR/traces.otf2 | LC_ALL=C grep '^\(ENTER\|LEAVE\) ' > trace.txt
 if [ x`grep -c Region1 trace.txt` = x4 ]; then
   if [ x`grep -v Region1 trace.txt | grep -v main | grep -v Region2` = x ]; then
-    rm -rf trace.txt $RESULT_DIR
     exit 0;
   else
     echo "Unexpected events detected in trace:"
     echo "`grep -v Region1 trace.txt | grep -v main`"
-    rm trace.txt
     exit 1
   fi
 fi
 
 echo "Uncorrect number of events for 'Region1'."
 echo "4 expected but `grep -c Region1 trace.txt` occured"
-rm trace.txt
 exit 1
 
 
diff --git a/test/filtering/run_filter_f_test.sh.in b/test/filtering/run_filter_f_test.sh.in
--- a/test/filtering/run_filter_f_test.sh.in
+++ b/test/filtering/run_filter_f_test.sh.in
@@ -18,13 +18,17 @@
 ## file       run_filter_test.sh
 ## maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 
-# Get SRC_ROOT and OTF2_PRINT
-make clean-local-scorep-config-tool
-make scorep-config-tool-local
-. ./scorep_config.dat
-
+OTF2_PRINT=@OTF2_BINDIR@/otf2-print
+SRC_ROOT=@abs_top_srcdir@/..
 RESULT_DIR=scorep-filter-f-test-dir
-rm -rf $RESULT_DIR
+
+cleanup()
+{
+    rm -rf scorep-measurement-tmp
+    rm -rf $RESULT_DIR
+    rm -f trace.txt
+}
+trap cleanup EXIT
 
 #-------------------------------------------------------------
 #                                          Fortran Filter test
@@ -37,7 +41,7 @@ SCOREP_ENABLE_TRACING=true \
 SCOREP_FILTERING_FILE=$SRC_ROOT/test/filtering/filter_f.cfg \
 ./filter_f_test
 if [ $? -ne 0 ]; then
-    rm -rf scorep-measurement-tmp start_ls.log
+    echo "./filter_f_test returned with errors"
     exit 1
 fi
 
@@ -49,45 +53,38 @@ $OTF2_PRINT $RESULT_DIR/traces.otf2 | LC_ALL=C grep '^\(ENTER\|LEAVE\) ' > trace
 if [ "`grep foo trace.txt`" ]; then
     echo "The following events should be filtered:"
     grep foo trace.txt
-    rm trace.txt
     exit 1
 fi
 
 if [ "`grep FOO trace.txt`" ]; then
     echo "The following events should be filtered:"
     grep FOO trace.txt
-    rm trace.txt
     exit 1
 fi
 
 if [ "`grep bar trace.txt`" ]; then
     echo "The following events should be filtered:"
     grep bar trace.txt
-    rm trace.txt
     exit 1
 fi
 
 if [ "`grep BAR trace.txt`" ]; then
     echo "The following events should be filtered:"
     grep BAR trace.txt
-    rm trace.txt
     exit 1
 fi
 
 if [ "`grep baz trace.txt`" ]; then
     echo "The following events should be filtered:"
     grep baz trace.txt
-    rm trace.txt
     exit 1
 fi
 
 if [ "`grep BAZ trace.txt`" ]; then
     echo "The following events should be filtered:"
     grep BAZ trace.txt
-    rm trace.txt
     exit 1
 fi
 
-rm -rf $RESULT_DIR
 exit 0
 
diff --git a/test/filtering/run_filter_test.sh.in b/test/filtering/run_filter_test.sh.in
--- a/test/filtering/run_filter_test.sh.in
+++ b/test/filtering/run_filter_test.sh.in
@@ -19,13 +19,18 @@
 ## maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 
 # Get SRC_ROOT and OTF2_PRINT
-make clean-local-scorep-config-tool
-make scorep-config-tool-local
-. ./scorep_config.dat
 
-
+OTF2_PRINT=@OTF2_BINDIR@/otf2-print
+SRC_ROOT=@abs_top_srcdir@/..
 RESULT_DIR=scorep-filter-test-dir
-rm -rf $RESULT_DIR
+
+cleanup()
+{
+    rm -rf scorep-measurement-tmp
+    rm -rf $RESULT_DIR
+    rm -f trace.txt
+}
+trap cleanup EXIT
 
 #-------------------------------------------------------------
 #                                                C Filter test
@@ -34,11 +39,9 @@ rm -rf $RESULT_DIR
 # Execute filter test
 SCOREP_EXPERIMENT_DIRECTORY=$RESULT_DIR SCOREP_ENABLE_PROFILING=false SCOREP_ENABLE_TRACING=true SCOREP_FILTERING_FILE=$SRC_ROOT/test/filtering/filter.cfg ./filter_test
 if [ $? -ne 0 ]; then
-    rm -rf scorep-measurement-tmp start_ls.log
+    echo "Execution of filter_test returned with errors"
     exit 1
 fi
-
-$OTF2_PRINT -A $RESULT_DIR/traces.otf2
 
 # Check output
 $OTF2_PRINT $RESULT_DIR/traces.otf2 | LC_ALL=C grep '^\(ENTER\|LEAVE\) ' > trace.txt
@@ -46,28 +49,23 @@ $OTF2_PRINT $RESULT_DIR/traces.otf2 | LC_ALL=C grep '^\(ENTER\|LEAVE\) ' > trace
 if [ "`grep filtered trace.txt`" ]; then
     echo "The following events should be filtered:"
     grep filtered trace.txt
-    rm trace.txt
     exit 1
 fi
 
 if [ "x`grep main trace.txt`" = "x" ]; then
     echo "The main function should not be filtered."
-    rm trace.txt
     exit 1
 fi
 
 if [ "x`grep filter_not1 trace.txt`" = "x" ]; then
     echo "The filter_not1 function should not be filtered."
-    rm trace.txt
     exit 1
 fi
 
 if [ "x`grep filter_not2 trace.txt`" = "x" ]; then
     echo "The filter_not2 function should not be filtered."
-    rm trace.txt
     exit 1
 fi
 
-rm -rf $RESULT_DIR
 exit 0
 
